version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Run test
          command: bundle exec rspec spec/ --format documentation

workflows:
  version: 2
  workflows:
    jobs:
      - test