version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: ci_rails_sample_test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: bundle exec rake db:schema:load
      - run: 
          name: テストの実行
          command: bundle exec rspec spec/ --format documentation


workflows:
  version: 2
  workflows:
    jobs:
      - test