version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.7-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.22
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: db/test.sqlite3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: bundle install
          command: |
            gem install bundler -v 2.1.4
            bundle install
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: bundle exec rake db:schema:load
      - run: 
          name: テストの実行
          command: bundle exec rspec spec/ --format documentation


workflows:
  version: 2
  workflows:
    jobs:
      - test